# Generated by Django 4.2.1 on 2023-06-12 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guilds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('reminder_template', models.TextField()),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guilds.guild')),
                ('reminder_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guilds.guildchannel')),
            ],
        ),
        migrations.CreateModel(
            name='CourseReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('published', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_reminders.course')),
            ],
        ),
    ]
