# Generated by Django 4.2.1 on 2023-07-09 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("discord_guilds", "0001_initial"),
        ("scheduler", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledPoll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published", models.BooleanField(default=False)),
                ("publish_time", models.DateTimeField()),
                ("reaction_type", models.CharField(default="yes_no", max_length=20)),
                (
                    "num_options",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (None, 0),
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                        ],
                        default=3,
                        null=True,
                    ),
                ),
                (
                    "guild_channel",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="discord_guilds.guildchannel",
                    ),
                ),
            ],
        ),
    ]
